
---
applications:
- name: fs-intake-api
  path: ../../../server
  buildpack: https://github.com/cloudfoundry/nodejs-buildpack
  memory: 256M
  instances: 1
  services:
    - eauth-service-provider
    - intake-client-service
    - intake-db
    - intake-s3
    - login-service-provider
    - middlelayer-service
    - smtp-service
    - pay-gov
    - jwt
