machine:
  node:
    version: 6
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/frontend/node_modules/.bin" # yarn
dependencies:
  pre:
    - rm -rf ~/.yarn
    - npm i -g yarn
    - yarn -v
    - yarn global add typedoc
    # chrome
    - curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome.deb
    - sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
    - rm google-chrome.deb
  override:
    - ./run-builds.sh
  cache_directories:
    - ~/.cache/yarn
compile:
  override:
    - cd frontend; yarn run docs;
    - cd frontend; yarn dist-staging;
test:
  pre:
    - cd frontend; npm install -g protractor
  override:
    - ./pa11y.sh
    - cd server; yarn run lint
    - cd server; yarn run snyk-test
    - cd server; yarn migrate
    - cd server; yarn seed-ci
    - cd server; yarn seed
    - cd server; yarn coverage
  #- cd frontend; yarn run lint
    - cd frontend; yarn run snyk-test
    - cd frontend; yarn run test:ci
    - ./run-e2e.sh;
  post:
    - cp -r frontend/coverage $CIRCLE_ARTIFACTS/
    - cp -r frontend/e2e-test-results $CIRCLE_ARTIFACTS/
    - mkdir $CIRCLE_ARTIFACTS/server-coverage
    - cp -r server/coverage $CIRCLE_ARTIFACTS/server-coverage/
deployment:
  prod:
    branch: master
    owner: 18F
    commands:
      - cd frontend; yarn run update-version;
      - cd frontend; yarn dist-prod;
      - ./cg-deploy/deploy.sh public-production
  staging:
    branch: sprint-15-development
    owner: flexion
    commands:
      - cd frontend; yarn run update-version;
      - cd frontend; yarn dist-staging;
      - ./cg-deploy/deploy.sh public-staging
  trees:
    branch: sprint-2-development
    owner: nciinc
    commands:
      - cd frontend; yarn run update-version;
      - cd frontend; yarn dist-trees;
      - ./cg-deploy/deploy.sh public-trees-staging
      